server:
  port: 8020

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neoflex-deal-db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true