server:
  port: 8020

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neoflex-deal-db
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false

  liquibase:
    enabled: true

rest:
  conveyor:
    url: http://localhost:8081
    endpoints:
      offers: conveyor/offers
      calculation: conveyor/calculation